/**********************************************************************************************************************
 * @description       : This is the custom exception class
 * @author            : Arka Jyoti Deb
 * @group             : 
 * @last modified on  : 12-21-2021
**********************************************************************************************************************/

public with sharing class CustomException extends Exception {

}