name: build

on:
  push:
    branches: ["master"]

  workflow_dispatch:
    inputs:
      name:
        description: Enter your name
        type: string
        required: true
      age:
        description: Enter your age
        type: number
      salary:
        description: Enter your salary
        type: number

jobs:

  build:
    runs-on: ubuntu-latest

    env:
      BRANCH_NAME: ${{ github.ref }}
      ENV_VAR: ${{ vars.ENV_VAR }}
      ENV_SECRET: ${{ secrets.ENV_SECRET }}
      NAME: ${{ github.events.inputs.name }}
      AGE: ${{ github.events.inputs.age }}
      SALARY: ${{ github.events.inputs.salary }}
    
    steps:
      - name: "Code Checkout"
        uses: actions/checkout@v4
      
      - name: "Install Python"
        uses: actions/setup-python@v5
        with:
          python-version: '3.10' 

      - name: "Display Greetings"
        run: chmod +x ./.github/lib/greetings.sh && sh ./.github/lib/greetings.sh
        shell: bash

  